// Generated by "bundle-dts@1.1.0" https://github.com/fishen/bundle-dts#readme."
declare module "examples/src/person" {
    export class Person {
        name: string;
        age: number;
        gender: boolean;
        address: string;
    }
}
declare module "examples/src/demo" {
    interface IDo {
        do(): void;
    }
    export class Demo implements IDo {
        do(): void;
    }
    export abstract class ADemo {
    }
    /**
     * 组件装饰器
     * @param options 组件装饰器参数
     */
    export function component<T = any>(options?: any): (constructor: new (...args: any[]) => any) => void;
    export {};
}
declare module "examples" {
    export { Person } from 'examples/src/person';
    export { Demo } from 'examples/src/demo';
}